name: zuupen
description: Een niet betaalde zuip app.

publish_to: "none"

version: 0.7.7+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^5.0.0
  cloud_firestore: ^3.1.6
  connectivity_plus: ^2.2.0
  feedback: ^2.4.0
  firebase_core: ^1.11.0
  firebase_storage: ^10.2.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.2
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.1.0
  google_fonts: ^3.0.1
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  package_info_plus: ^1.3.0
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.12

dev_dependencies:
  auto_route_generator: ^5.0.0
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - .env
