name: zuupen
description: Een niet betaalde zuip app.

publish_to: "none"

version: 0.5.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.2
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  dotenv: ^3.0.0
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_dotenv: ^5.0.2
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.1.0
  google_fonts: ^2.1.0
  html: ^0.15.0
  package_info_plus: ^1.3.0

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - .env
