name: zuupen
description: Een niet betaalde zuip app.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_switch: ^0.3.1
  font_awesome_flutter: ^9.0.0
  get: ^4.1.4
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
