name: zuupen
description: Een niet betaalde zuip app.

publish_to: "none"

version: 0.3.10+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  get: ^4.6.1
  google_fonts: ^2.1.0
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
