// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMSaD9pPBenZhtoI81N6RPK8lbYXXN-MU',
    appId: '1:619810693292:android:e76e9d1ed5c17d69dc7f09',
    messagingSenderId: '619810693292',
    projectId: 'zuupen-a42a6',
    storageBucket: 'zuupen-a42a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz1B0Rf3E5tu5rbpeK_bW5XKqGIyRy3Aw',
    appId: '1:619810693292:ios:1eab9e95fcf39ebedc7f09',
    messagingSenderId: '619810693292',
    projectId: 'zuupen-a42a6',
    storageBucket: 'zuupen-a42a6.appspot.com',
    iosClientId: '619810693292-8bmji57ecj6ko0k8lv82au8p6co63d8j.apps.googleusercontent.com',
    iosBundleId: 'nl.sastrokarijo.zuupen',
  );
}
